apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: gpu-operator
  labels:
    app: nvidia-device-plugin-daemonset
spec:
  selector:
    matchLabels:
      app: nvidia-device-plugin-daemonset
  template:
    metadata:
      labels:
        app: nvidia-device-plugin-daemonset
    spec:
      nodeSelector:
        nodeGroup: gpu-worker
      containers:
        - name: nvidia-device-plugin
          image: ghcr.io/mchmarny/smifaker:latest
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 30; done"]
          env:
            - name: SMIFAKER_CONTENT_PATH
              value: "/data/nvidia-smi.xml"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
      volumes:
        - name: data
          configMap:
            name: smi-faker-data
            items:
              - key: nvidia-smi.xml
                path: nvidia-smi.xml
      restartPolicy: Always
