apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuid
  namespace: node-labeler
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gpuid
          image: ghcr.io/mchmarny/gpuid:latest
