apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuid
  namespace: node-labeler
  labels:
    app: gpuid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpuid
  template:
    metadata:
      labels:
        app: gpuid
    spec:
      serviceAccountName: gpuid
      terminationGracePeriodSeconds: 10
      containers:
        - name: gpuid
          image: ghcr.io/mchmarny/gpuid:latest
          env:
            - name: ROLE_LABEL
              valueFrom:
                configMapKeyRef:
                  name: gpuid-config
                  key: roleLabel
            - name: ROLE_LABEL_REPLACE
              valueFrom:
                configMapKeyRef:
                  name: gpuid-config
                  key: roleReplace
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gpuid-config
                  key: logLevel
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
              name: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
