apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuid
  namespace: gpuid
  labels:
    app: gpuid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpuid
  template:
    metadata:
      labels:
        app: gpuid
    spec:
      serviceAccountName: gpuid
      containers:
        - name: gpuid
          image: ghcr.io/mchmarny/gpuid@sha256:9080d88115528838c81feaf9955dba5ef74067c628a0d065780eb5bc160361e3
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
              name: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
