apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuid
  namespace: gpuid
  labels:
    app: gpuid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpuid
  template:
    metadata:
      labels:
        app: gpuid
    spec:
      serviceAccountName: gpuid
      containers:
        - name: gpuid
          image: ghcr.io/mchmarny/gpuid:v0.7.1@sha256:a873be75b9e85ae144b2787a1ab755bf4a77ba4652ef919f3a95e1bbac2b462f
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
              name: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
