apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuid
  namespace: gpuid
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gpuid
          env:
            - name: CLUSTER_NAME
              value: 'validation'
            - name: EXPORTER_TYPE
              value: 'postgres'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: 'gpuid'
            - name: POSTGRES_TABLE
              value: 'serials'
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      tolerations:
        - key: dedicated
          operator: Equal
          value: system-workload