#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${DIR}/common"
ROOT=$(dirname "${DIR}")

# Assume current k8s context
IMAGE=$1
PATCH_FILE=$2

if [[ -z "$IMAGE" ]]; then
  err "Image not provided. Usage: $0 <image> <patch-file>"
fi

if [[ -z "$PATCH_FILE" ]]; then
  err "Patch file not provided. Usage: $0 <image> <patch-file>"
fi

if [[ ! -f "$PATCH_FILE" ]]; then
  err "Patch file $PATCH_FILE does not exist."
fi

msg "Setting image in $PATCH_FILE to $IMAGE"
sed -i "s|image: .*|image: $IMAGE|" "$PATCH_FILE"
